### ISSUE TITLE
Feature request: include soft decision trees like in SoftBart

### ISSUE THREAD

**Issue by wdkrnls** [gamlss-dev/gamlss2#3]
Please consider supporting "soft" decision tree ensembles like those in the SoftBart R package. That seems pretty on-point as a smoothing technique which would be exciting to have in a distributional regression context.

- [CRAN](https://cran.r-project.org/web/packages/SoftBart/index.html)
- [github](https://github.com/theodds/SoftBART)

**Comment by freezenik** [comment]
We are working on it

https://github.com/freezenik/softtrees

But this is still work in progress. The code is already outdated, I will update the package soon.
