### ISSUE TITLE
Is it possible to plot the effect after fitting with light=TRUE?

### ISSUE THREAD

**Issue by tmspvn** [gamlss-dev/gamlss2#8]
Hello,

it seems to me it is not possible to plot the effect when the parameter [light=TRUE](https://github.com/gamlss-dev/gamlss2/blob/804385da8b6907b91a6192ad29dd115534508137/R/gamlss2.R#L280) is set, since it will not run `results.gamlss2` thus [skipping the effect and plotting the diagnostic instead.](https://github.com/gamlss-dev/gamlss2/blob/804385da8b6907b91a6192ad29dd115534508137/R/plots.R#L39)

Therefore, I tried calling `results.gamlss2` without success: 
```

> amod$results <- gamlss2:::results.gamlss2(amod)
> plot(amod, which="effect")
Error in par(mfrow = if (nplts <= 4) c(1, nplts) else n2mfrow(nplts)) : 
  invalid value specified for graphical parameter "mfrow"
Warning message:
In par(owd) : calling par(new=TRUE) with no plot

```

However, I can't really test it further on toy data because there's a bug in the `plot()` call after adding `light=T`:

```
> data("abdom", package = "gamlss.data")
> f <- y ~ s(x) | s(x) | s(x) | s(x)
> b <- gamlss2(f, data = abdom, family = BCT, light=T)
Start estimation ...
GAMLSS-RS iteration  4: Global Deviance = 4770.1554 eps = 0.000002    
> plot(b)
Error in Predict.matrix.tprs.smooth(object, dk$data) : 
  'R_Calloc' could not allocate memory (18446744072510526370 of 8 bytes)

```

Is there a way to have an effects plot after fitting with light=T?

Thanks

**Comment by freezenik** [comment]
Thanks for catching this! This was because the predict() method was missing a smooth constructor element that I didn't know about! I fixed it now, it should work now.
